### ISSUE TITLE
Please add 'MIND: Multi-Task Incremental Network Distillation' accepted at AAAI 2024

### ISSUE THREAD

**Issue by jbonato1** [feifeiobama/Awesome-Continual-Learning#1]
Thanks for contributing such a great repository!

Would you please add the following paper published at AAAI 2024?

Paper title: MIND: Multi-Task Incremental Network Distillation
Paper link: https://arxiv.org/abs/2312.02916
Code link: https://github.com/Lsabetta/MIND
keywords: Replay-free Class Incremental learning, architectural based solutions

Thanks for your consideration!

**Comment by feifeiobama** [comment]
Thank you for sharing this paper. The repository has been updated accordingly.
