### ISSUE TITLE
Consider adding a survey paper to the list

### ISSUE THREAD

**Issue by LucyDYu** [feifeiobama/Awesome-Continual-Learning#7]
Hi, thank you for maintaining this valuable repository.

Could you please add the following survey paper to this paper list:
Recent Advances of Multimodal Continual Learning: A Comprehensive Survey https://arxiv.org/abs/2410.05352.

Thank you for your consideration!

**Comment by feifeiobama** [comment]
Thank you for the contribution. The survey paper has been added in commit https://github.com/feifeiobama/Awesome-Continual-Learning/commit/0bf858241787ed7258db771e1f6556e47e25f5cb.
